/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/VoOYJzqjCdL
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { TsxExclude } from "@/types/helpers"
import Image from "next/image"

export function PortfolioLanding() {
  return (
    <div className="min-h-[100dvh] flex flex-col dark">
      <section className="bg-gray-950 py-12 md:py-24 flex items-center justify-center">
        <div className="container px-4 md:px-6 text-center space-y-6">
          <div className="flex items-center justify-center">
            <div className="w-24 h-24 md:w-32 md:h-32 rounded-full bg-gradient-to-r from-indigo-500 to-pink-500 flex items-center justify-center">
              <span className="text-4xl md:text-5xl font-bold text-white">JD</span>
            </div>
          </div>
          <div className="space-y-2">
            <h1 className="text-4xl sm:text-5xl md:text-6xl font-bold tracking-tighter text-white">John Doe</h1>
            <p className="text-gray-400 max-w-[600px] mx-auto md:text-xl">
              I'm a passionate web developer with a focus on building beautiful and functional websites.
            </p>
          </div>
        </div>
      </section>
      <section className="py-12 md:py-24">
        <div className="container px-4 md:px-6">
          <div className="space-y-4 md:space-y-6">
            <div className="space-y-2">
              <h2 className="text-4xl sm:text-5xl md:text-6xl font-bold tracking-tighter">Featured Projects</h2>
              <p className="text-gray-400 max-w-[600px] md:text-xl">
                Check out some of my recent web development projects.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              <div className="bg-gray-950 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow">
                <Image
                  alt="Project 1"
                  className="w-full h-[225px] object-cover"
                  height="225"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/225",
                    objectFit: "cover",
                  }}
                  width="400"
                />
                <div className="p-4 space-y-2">
                  <h3 className="text-lg font-semibold">Project 1</h3>
                  <p className="text-gray-400 line-clamp-2">A modern and responsive website for a local business.</p>
                </div>
              </div>
              <div className="bg-gray-950 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow">
                <Image
                  alt="Project 2"
                  className="w-full h-[225px] object-cover"
                  height="225"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/225",
                    objectFit: "cover",
                  }}
                  width="400"
                />
                <div className="p-4 space-y-2">
                  <h3 className="text-lg font-semibold">Project 2</h3>
                  <p className="text-gray-400 line-clamp-2">A custom e-commerce platform for a small online store.</p>
                </div>
              </div>
              <div className="bg-gray-950 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow">
                <Image
                  alt="Project 3"
                  className="w-full h-[225px] object-cover"
                  height="225"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/225",
                    objectFit: "cover",
                  }}
                  width="400"
                />
                <div className="p-4 space-y-2">
                  <h3 className="text-lg font-semibold">Project 3</h3>
                  <p className="text-gray-400 line-clamp-2">
                    A personal blog built with a modern content management system.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="bg-gray-950 py-12 md:py-24">
        <div className="container px-4 md:px-6">
          <div className="space-y-4 md:space-y-6">
            <div className="space-y-2">
              <h2 className="text-4xl sm:text-5xl md:text-6xl font-bold tracking-tighter text-white">Skills</h2>
              <p className="text-gray-400 max-w-[600px] md:text-xl">
                Here are some of the technologies I'm proficient in.
              </p>
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
              <div className="bg-gray-900 rounded-lg p-4 flex flex-col items-center justify-center space-y-2">
                <TextIcon className="w-8 h-8 text-white" />
                <span className="text-sm font-medium text-white">HTML</span>
              </div>
              <div className="bg-gray-900 rounded-lg p-4 flex flex-col items-center justify-center space-y-2">
                <ChromeIcon className="w-8 h-8 text-white" />
                <span className="text-sm font-medium text-white">CSS</span>
              </div>
              <div className="bg-gray-900 rounded-lg p-4 flex flex-col items-center justify-center space-y-2">
                <CodepenIcon className="w-8 h-8 text-white" />
                <span className="text-sm font-medium text-white">JavaScript</span>
              </div>
              <div className="bg-gray-900 rounded-lg p-4 flex flex-col items-center justify-center space-y-2">
                <ComponentIcon className="w-8 h-8 text-white" />
                <span className="text-sm font-medium text-white">React</span>
              </div>
              <div className="bg-gray-900 rounded-lg p-4 flex flex-col items-center justify-center space-y-2">
                <WindIcon className="w-8 h-8 text-white" />
                <span className="text-sm font-medium text-white">Tailwind CSS</span>
              </div>
              <div className="bg-gray-900 rounded-lg p-4 flex flex-col items-center justify-center space-y-2">
                <NetworkIcon className="w-8 h-8 text-white" />
                <span className="text-sm font-medium text-white">Node.js</span>
              </div>
              <div className="bg-gray-900 rounded-lg p-4 flex flex-col items-center justify-center space-y-2">
                <GitGraphIcon className="w-8 h-8 text-white" />
                <span className="text-sm font-medium text-white">Git</span>
              </div>
              <div className="bg-gray-900 rounded-lg p-4 flex flex-col items-center justify-center space-y-2">
                <FigmaIcon className="w-8 h-8 text-white" />
                <span className="text-sm font-medium text-white">Figma</span>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="py-12 md:py-24">
        <div className="container px-4 md:px-6">
          <div className="space-y-4 md:space-y-6">
            <div className="space-y-2">
              <h2 className="text-4xl sm:text-5xl md:text-6xl font-bold tracking-tighter">Blog</h2>
              <p className="text-gray-400 max-w-[600px] md:text-xl">Check out my latest blog posts.</p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              <div className="bg-gray-950 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow">
                <Image
                  alt="Blog Post 1"
                  className="w-full h-[225px] object-cover"
                  height="225"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/225",
                    objectFit: "cover",
                  }}
                  width="400"
                />
                <div className="p-4 space-y-2">
                  <h3 className="text-lg font-semibold">Blog Post 1</h3>
                  <p className="text-gray-400 line-clamp-2">
                    A deep dive into the latest web development trends and technologies.
                  </p>
                  <Link
                    className="inline-flex items-center justify-center rounded-md bg-gray-50 px-4 py-2 text-sm font-medium text-gray-900 shadow transition-colors hover:bg-gray-50/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-300 disabled:pointer-events-none disabled:opacity-50"
                    href="#"
                  >
                    Read More
                  </Link>
                </div>
              </div>
              <div className="bg-gray-950 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow">
                <Image
                  alt="Blog Post 2"
                  className="w-full h-[225px] object-cover"
                  height="225"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/225",
                    objectFit: "cover",
                  }}
                  width="400"
                />
                <div className="p-4 space-y-2">
                  <h3 className="text-lg font-semibold">Blog Post 2</h3>
                  <p className="text-gray-400 line-clamp-2">
                    Exploring the benefits of using a modern CSS framework like Tailwind CSS.
                  </p>
                  <Link
                    className="inline-flex items-center justify-center rounded-md bg-gray-50 px-4 py-2 text-sm font-medium text-gray-900 shadow transition-colors hover:bg-gray-50/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-300 disabled:pointer-events-none disabled:opacity-50"
                    href="#"
                  >
                    Read More
                  </Link>
                </div>
              </div>
              <div className="bg-gray-950 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow">
                <Image
                  alt="Blog Post 3"
                  className="w-full h-[225px] object-cover"
                  height="225"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/225",
                    objectFit: "cover",
                  }}
                  width="400"
                />
                <div className="p-4 space-y-2">
                  <h3 className="text-lg font-semibold">Blog Post 3</h3>
                  <p className="text-gray-400 line-clamp-2">
                    Mastering the art of responsive web design with modern techniques.
                  </p>
                  <Link
                    className="inline-flex items-center justify-center rounded-md bg-gray-50 px-4 py-2 text-sm font-medium text-gray-900 shadow transition-colors hover:bg-gray-50/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-300 disabled:pointer-events-none disabled:opacity-50"
                    href="#"
                  >
                    Read More
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="py-12 md:py-24">
        <div className="container px-4 md:px-6">
          <div className="space-y-4 md:space-y-6">
            <div className="space-y-2">
              <h2 className="text-4xl sm:text-5xl md:text-6xl font-bold tracking-tighter">Contact</h2>
              <p className="text-gray-400 max-w-[600px] md:text-xl">
                Feel free to reach out to me through any of the following channels.
              </p>
            </div>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link
                className="inline-flex items-center justify-center rounded-md bg-gray-50 px-4 py-2 text-sm font-medium text-gray-900 shadow transition-colors hover:bg-gray-50/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-300 disabled:pointer-events-none disabled:opacity-50"
                href="#"
              >
                <GithubIcon className="mr-2 h-5 w-5" />
                GitHub
              </Link>
              <Link
                className="inline-flex items-center justify-center rounded-md bg-gray-50 px-4 py-2 text-sm font-medium text-gray-900 shadow transition-colors hover:bg-gray-50/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-300 disabled:pointer-events-none disabled:opacity-50"
                href="#"
              >
                <LinkedinIcon className="mr-2 h-5 w-5" />
                LinkedIn
              </Link>
              <Link
                className="inline-flex items-center justify-center rounded-md bg-gray-50 px-4 py-2 text-sm font-medium text-gray-900 shadow transition-colors hover:bg-gray-50/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-300 disabled:pointer-events-none disabled:opacity-50"
                href="#"
              >
                <TwitterIcon className="mr-2 h-5 w-5" />
                Twitter
              </Link>
            </div>
          </div>
        </div>
      </section>
      <footer className="bg-gray-950 py-6 mt-auto">
        <div className="container px-4 md:px-6 flex items-center justify-between">
          <p className="text-gray-400 text-sm">© 2024 John Doe. All rights reserved.</p>
          <Button
            className="flex items-center gap-2 text-gray-400 hover:text-gray-50 transition-colors"
            size="sm"
            variant="outline"
          >
            <ArrowUpIcon className="w-4 h-4" />
            Back to Top
          </Button>
        </div>
      </footer>
    </div>
  )
}

function ArrowUpIcon({...props}: TsxExclude<"svg", "xmlns" | "viewBox" | "fill">) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m5 12 7-7 7 7" />
      <path d="M12 19V5" />
    </svg>
  )
}


function ChromeIcon({...props}: TsxExclude<"svg", "xmlns" | "viewBox" | "fill">) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>
  )
}


function CodepenIcon({...props}: TsxExclude<"svg", "xmlns" | "viewBox" | "fill">) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 22 8.5 22 15.5 12 22 2 15.5 2 8.5 12 2" />
      <line x1="12" x2="12" y1="22" y2="15.5" />
      <polyline points="22 8.5 12 15.5 2 8.5" />
      <polyline points="2 15.5 12 8.5 22 15.5" />
      <line x1="12" x2="12" y1="2" y2="8.5" />
    </svg>
  )
}


function ComponentIcon({...props}: TsxExclude<"svg", "xmlns" | "viewBox" | "fill">) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5.5 8.5 9 12l-3.5 3.5L2 12l3.5-3.5Z" />
      <path d="m12 2 3.5 3.5L12 9 8.5 5.5 12 2Z" />
      <path d="M18.5 8.5 22 12l-3.5 3.5L15 12l3.5-3.5Z" />
      <path d="m12 15 3.5 3.5L12 22l-3.5-3.5L12 15Z" />
    </svg>
  )
}


function FigmaIcon({...props}: TsxExclude<"svg", "xmlns" | "viewBox" | "fill">) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 5.5A3.5 3.5 0 0 1 8.5 2H12v7H8.5A3.5 3.5 0 0 1 5 5.5z" />
      <path d="M12 2h3.5a3.5 3.5 0 1 1 0 7H12V2z" />
      <path d="M12 12.5a3.5 3.5 0 1 1 7 0 3.5 3.5 0 1 1-7 0z" />
      <path d="M5 19.5A3.5 3.5 0 0 1 8.5 16H12v3.5a3.5 3.5 0 1 1-7 0z" />
      <path d="M5 12.5A3.5 3.5 0 0 1 8.5 9H12v7H8.5A3.5 3.5 0 0 1 5 12.5z" />
    </svg>
  )
}


function GitGraphIcon({...props}: TsxExclude<"svg", "xmlns" | "viewBox" | "fill">) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="5" cy="6" r="3" />
      <path d="M5 9v6" />
      <circle cx="5" cy="18" r="3" />
      <path d="M12 3v18" />
      <circle cx="19" cy="6" r="3" />
      <path d="M16 15.7A9 9 0 0 0 19 9" />
    </svg>
  )
}


function GithubIcon({...props}: TsxExclude<"svg", "xmlns" | "viewBox" | "fill">) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function LinkedinIcon({...props}: TsxExclude<"svg", "xmlns" | "viewBox" | "fill">) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function NetworkIcon({...props}: TsxExclude<"svg", "xmlns" | "viewBox" | "fill">) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="16" y="16" width="6" height="6" rx="1" />
      <rect x="2" y="16" width="6" height="6" rx="1" />
      <rect x="9" y="2" width="6" height="6" rx="1" />
      <path d="M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3" />
      <path d="M12 12V8" />
    </svg>
  )
}


function TextIcon({...props}: TsxExclude<"svg", "xmlns" | "viewBox" | "fill">) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 6.1H3" />
      <path d="M21 12.1H3" />
      <path d="M15.1 18H3" />
    </svg>
  )
}


function TwitterIcon({...props}: TsxExclude<"svg", "xmlns" | "viewBox" | "fill">) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function WindIcon({...props}: TsxExclude<"svg", "xmlns" | "viewBox" | "fill">) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.7 7.7a2.5 2.5 0 1 1 1.8 4.3H2" />
      <path d="M9.6 4.6A2 2 0 1 1 11 8H2" />
      <path d="M12.6 19.4A2 2 0 1 0 14 16H2" />
    </svg>
  )
}
