/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/isELiH5dBCz
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Bricolage_Grotesque } from 'next/font/google'
import { Syne } from 'next/font/google'

bricolage_grotesque({
  subsets: ['latin'],
  display: 'swap',
})

syne({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import type { TsxExcludeExp } from "@/types/helpers";

export function SearchComponent() {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant='outline'>Open Search</Button>
      </DialogTrigger>
      <DialogContent className='sm:max-w-[600px]'>
        <DialogHeader>
          <DialogTitle>Search</DialogTitle>
          <DialogDescription>
            Find what you're looking for with our powerful search.
          </DialogDescription>
        </DialogHeader>
        <div className='space-y-4 p-4'>
          <div className='relative'>
            <SearchIcon className='absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-500 dark:text-gray-400' />
            <Input
              className='w-full placeholder-gray-500 appearance-none rounded-md bg-white pl-10 shadow-none dark:bg-gray-950'
              placeholder='Search for products...'
              type='search'
            />
          </div>
          <div className='grid gap-4'>
            <div>
              <h3 className='text-lg font-semibold'>Suggestions</h3>
              <div className='mt-2 space-y-2' />
            </div>
            <div>
              <h3 className='text-lg font-semibold'>Results</h3>
              <div className='mt-2 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3' />
            </div>
          </div>
        </div>
        <DialogFooter>
          <div>
            <Button variant='outline'>Close</Button>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function SearchIcon({
  ...props
}: TsxExcludeExp<"attribute", "svg", "viewBox" | "xmlns" | "fill">) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'>
      <circle cx='11' cy='11' r='8' />
      <path d='m21 21-4.3-4.3' />
    </svg>
  );
}
